from PIL import Image
import numpy as np
# config_default.py

configs={
    'firstsuit':[r'depu\samples\first_suit\1_s.png',
                r'depu\samples\first_suit\1_h.png',
                r'depu\samples\first_suit\1_c.png',
                r'depu\samples\first_suit\1_d.png'],
    'firstnum':[r'depu\samples\first_num\1_2.png', 
                r'depu\samples\first_num\1_3.png', 
                r'depu\samples\first_num\1_4.png', 
                r'depu\samples\first_num\1_5.png', 
                r'depu\samples\first_num\1_6.png', 
                r'depu\samples\first_num\1_7.png', 
                r'depu\samples\first_num\1_8.png', 
                r'depu\samples\first_num\1_9.png', 
                r'depu\samples\first_num\1_t.png', 
                r'depu\samples\first_num\1_j.png', 
                r'depu\samples\first_num\1_q.png', 
                r'depu\samples\first_num\1_k.png', 
                r'depu\samples\first_num\1_a.png' ],
    'secondsuit':[r'depu\samples\second_suit\2_s.png',
                r'depu\samples\second_suit\2_h.png',
                r'depu\samples\second_suit\2_c.png',
                r'depu\samples\second_suit\2_d.png'],
    'secondnum':[r'depu\samples\second_num\2_2.png', 
                r'depu\samples\second_num\2_3.png',
                r'depu\samples\second_num\2_4.png',
                r'depu\samples\second_num\2_5.png',
                r'depu\samples\second_num\2_6.png',
                r'depu\samples\second_num\2_7.png',
                r'depu\samples\second_num\2_8.png',
                r'depu\samples\second_num\2_9.png',
                r'depu\samples\second_num\2_t.png',
                r'depu\samples\second_num\2_j.png',
                r'depu\samples\second_num\2_q.png',
                r'depu\samples\second_num\2_k.png',
                r'depu\samples\second_num\2_a.png' ],
    'pubsuit':[r'depu\samples\pub_suit\p_s.png',
                r'depu\samples\pub_suit\p_h.png',
                r'depu\samples\pub_suit\p_c.png',
                r'depu\samples\pub_suit\p_d.png'],
    'pubnum':[r'depu\samples\pub_num\p_2.png',
                r'depu\samples\pub_num\p_3.png',
                r'depu\samples\pub_num\p_4.png',
                r'depu\samples\pub_num\p_5.png',
                r'depu\samples\pub_num\p_6.png',
                r'depu\samples\pub_num\p_7.png',
                r'depu\samples\pub_num\p_8.png',
                r'depu\samples\pub_num\p_9.png',
                r'depu\samples\pub_num\p_t.png',
                r'depu\samples\pub_num\p_j.png',
                r'depu\samples\pub_num\p_q.png',
                r'depu\samples\pub_num\p_k.png',
                r'depu\samples\pub_num\p_a.png',
                r'depu\samples\pub_num\p_tr.png',
                r'depu\samples\pub_num\p_8r.png',
                r'depu\samples\pub_num\p_qr.png'],
    'dcnum': [r'depu\samples\dc_num\dc_0.png', 
                r'depu\samples\dc_num\dc_1.png', 
                r'depu\samples\dc_num\dc_2.png', 
                r'depu\samples\dc_num\dc_3.png', 
                r'depu\samples\dc_num\dc_4.png', 
                r'depu\samples\dc_num\dc_5.png', 
                r'depu\samples\dc_num\dc_6.png', 
                r'depu\samples\dc_num\dc_7.png', 
                r'depu\samples\dc_num\dc_8.png', 
                r'depu\samples\dc_num\dc_9.png', 
                r'depu\samples\dc_num\dc_dot.png', 
                r'depu\samples\dc_num\dc_wan.png', 
                r'depu\samples\dc_num\dc_slash.png' ],
    'chipnum': [r'depu\samples\chip_num\chip_0.png', 
                    r'depu\samples\chip_num\chip_1.png', 
                    r'depu\samples\chip_num\chip_2.png', 
                    r'depu\samples\chip_num\chip_3.png', 
                    r'depu\samples\chip_num\chip_4.png', 
                    r'depu\samples\chip_num\chip_5.png', 
                    r'depu\samples\chip_num\chip_6.png', 
                    r'depu\samples\chip_num\chip_7.png', 
                    r'depu\samples\chip_num\chip_8.png', 
                    r'depu\samples\chip_num\chip_9.png', 
                    r'depu\samples\chip_num\chip_dot.png',
                    r'depu\samples\chip_num\chip_wan.png'],
    'status': [r'depu\samples\status\status_fold.png', 
                    r'depu\samples\status\status_check.png', 
                    r'depu\samples\status\status_call.png', 
                    r'depu\samples\status\status_raise.png'],
    'btn': [r'depu\samples\btn_sample.png'],
    'callnum': [r'depu\samples\call_num\call_0.png', 
                r'depu\samples\call_num\call_1.png', 
                r'depu\samples\call_num\call_2.png', 
                r'depu\samples\call_num\call_3.png', 
                r'depu\samples\call_num\call_4.png', 
                r'depu\samples\call_num\call_5.png', 
                r'depu\samples\call_num\call_6.png', 
                r'depu\samples\call_num\call_7.png', 
                r'depu\samples\call_num\call_8.png', 
                r'depu\samples\call_num\call_9.png', 
                r'depu\samples\call_num\call_dot.png', 
                r'depu\samples\call_num\call_wan.png' ]
}

npconfigs = {}
for key in configs:
    arrs = configs[key]
    r = []
    for filename in arrs:
        img=Image.open(filename).convert('L')
        r.append(np.array(img))
    npconfigs[key] = r
    